### ISSUE TITLE
User has no active card

### ISSUE THREAD

**Issue by Skyd3v** [imZephox/blocipedia#7]
Hello John..

I am trying to downgrade accounts with Stripe,I believe implementations has been done correct but when I downgrade an account which in theory should destroy the Stripe methods and redirect me as a current user I am getting a Cannot charge a customer that has no active card error.

Can you please help me out and tell me where I am doing something wrong?
Was looking online and apparently the error has to do with the stripe token but never found a clear answer...

I can upgrade fine and can see user becoming premium but with the latest commit I seem to be stuck..

**Comment by johnksawers** [comment]
I'll need a bit of clarification. Are you saying that when you click 'downgrade' which calls ChargesController#destroy you get a Rails error page with the 'no active card' error?

Also, is the code on GitHub in the stripe branch the code where you're seeing the issue?

If you could post the stack trace from the error that would be incredibly helpful. The stack trace is the first place to start with any bug report, or any debugging task.

**Comment by Skyd3v** [comment]
Hello John,the code where I am seeing the error is on commit ""stripe error when downgrading.''

I receive no red pages as you would expect from a controller error point of view.There are no traces on the console at all(hence I am going mental).Everything seems to be working fine.
<img width="1393" alt="screen shot 2016-12-01 at 22 01 26" src="https://cloud.githubusercontent.com/assets/20864379/20814513/cc0c4f6c-b811-11e6-9755-5a18e80d4e82.png">


Here you can see what is going on with my console 

<img width="977" alt="screen shot 2016-12-01 at 22 02 46" src="https://cloud.githubusercontent.com/assets/20864379/20814540/f31d470a-b811-11e6-96ef-6044fa73ef02.png">

It is driving me insane as I read everywhere it has to do with the token on charges controller,tried the majority of suggested fixes yet facing the same problem which makes me think it could be because we are on a test environment and not live on stripe API...

**Comment by johnksawers** [comment]
From looking at those logs none of those requests are DELETE verbs, which means none of them are hitting the destroy method in ChargesController. 

That made me take a closer look at the Downgrade button. The method is :destroy, when it should be :delete

It's a confusing part of rails - the HTTP Verb is 'delete' but the method in teh controller is always 'destroy'

**Comment by Skyd3v** [comment]
Already tried that before but getting a routing error when my routes seem to be configured correct...

<img width="949" alt="screen shot 2016-12-01 at 22 20 32" src="https://cloud.githubusercontent.com/assets/20864379/20815107/7c8fa26a-b814-11e6-9df6-12daf5cb0f68.png">

**Comment by johnksawers** [comment]
Looking at the routes I finally figured it out. By default all destroy routes requires an ID be passed to it (so that it can destroy a specific model instance). You can see that by looking at the 'path' column for destroy charge_path, the path is '/charges/:id/' the symbol in there means that you need to pass it an ID. So, because your ChargesController#destroy method doesn't require a charge ID we'll need to change that from the default. 

The first option is to realize that you're not actually destroying a charge, you're not talking to Stripe at all (which is fine), you are in fact just updating the user's role. So it might make more sense to take the body of the destroy method and move it to a new method in UsersController called 'downgrade' - then add a route for that which will look liked this: 

```
resources :users, only: [:show] do
   patch '/downgrade', to: 'Users#downgrade'
end
```

The other option is to keep it as similar to what you have as possible, leave it where it is and change the routes to something like the this:

```
resources :charges, only: [:new, :create] do
   delete '/destroy', to: 'Charges#destroy'
end
````

**Comment by imZephox** [comment]
Not to be pessimistic or anything...I tried everything you have suggested..

Yes receiving the same error in terms of the user has no active card...Have been stack overflowing and even asked today at work for some help,but without success..
